export const excludedLogos = ['BTO.png', 'cemevi.png']

export const referenceNameOverrides: Record<string, string> = {
  'Arnavutlukköy belediyesi.png': 'Arnavutköy Belediyesi',
  'autopia.png': 'Autopia',
  'Bakırköy kaymakamlığı.png': 'Bakırköy Kaymakamlığı',
  'Bakıröy Belediyesi.png': 'Bakırköy Belediyesi',
  'balıkesir Hiltonn.jpeg': 'Hilton Garden Inn Balıkesir',
  'başakkent.png': 'Başakkent',
  'başakşehir belediyesi.png': 'Başakşehir Belediyesi',
  'Beyoğlu kaymakamlığı.png': 'Beyoğlu Kaymakamlığı',
  'Buyukcekmece Belediyesi.png': 'Büyükçekmece Belediyesi',
  'buzadası.png': 'Buz Adası',
  'byuas.png': 'BYUAŞ',
  'Crowne Plaza.png': 'Crowne Plaza',
  'Darica belediyesi.png': 'Darıca Belediyesi',
  'Darıca belediyesi.png': 'Darıca Belediyesi',
  'demirbank-logo.svg': 'Demirbank',
  'esenler belediyesi.png': 'Esenler Belediyesi',
  'eskon.png': 'ESKON A.Ş.',
  'eyupsultan belediyesi.png': 'Eyüpsultan Belediyesi',
  'Gaziosmanpasa belediyesi.png': 'Gaziosmanpaşa Belediyesi',
  'İstanbul Akvaryum.png': 'İstanbul Akvaryum',
  'İstanbul_Başakşehir_FK (1).png': 'İstanbul Başakşehir FK / Fatih Terim Stadyumu',
  'İstanbul Valiliği.png': 'T.C. İstanbul Valiliği',
  'marmara teknokent.png': 'Marmara Teknokent (MARTEK)',
  'Matbaacılar sitesi.png': '2.Matbaacılar Sitesi',
  'Metropark awm.png': 'Metropark AVM',
  'nefes-orman-logo.png': 'Nefes Orman',
  'parkekspert.png': 'ParkEkspert',
  'sarfit.jpg': 'Sarfit',
  'Sarıyer Belediyesi.png': 'Sarıyer Belediyesi',
  'Trik center.png': 'Triko Center',
  'Vema Holding.png': 'Vema Holding',
  'YTÜ.png': 'Yıldız Teknik Üniversitesi (YTÜ)',
  'ytü Yıldız teknopark.png': 'YTÜ Yıldız Teknopark',
  'Intetra.png': 'Intetra',
}

export const referenceWebsiteOverrides: Record<string, string | null> = {
  'Arnavutlukköy belediyesi.png': 'https://www.arnavutkoy.bel.tr',
  'autopia.png': null,
  'Bakırköy kaymakamlığı.png': 'https://www.bakirkoy.gov.tr',
  'Bakıröy Belediyesi.png': 'https://www.bakirkoy.bel.tr',
  'balıkesir Hiltonn.jpeg': 'https://www.hilton.com/tr/',
  'başakkent.png': 'https://www.basakkent.com.tr',
  'başakşehir belediyesi.png': 'https://www.basaksehir.bel.tr',
  'Beyoğlu kaymakamlığı.png': 'https://www.beyoglu.gov.tr',
  'Buyukcekmece Belediyesi.png': 'https://www.buyukcekmece.bel.tr',
  'buzadası.png': 'https://www.buzadasi.com',
  'byuas.png': 'http://www.bakirkoyyapi.com',
  'Crowne Plaza.png': 'https://www.cpistanbulflorya.com',
  'Darıca belediyesi.png': 'https://www.darica.bel.tr',
  'Darica belediyesi.png': 'https://www.darica.bel.tr',
  'demirbank-logo.svg': 'https://www.demirbank.kg/',
  'eskon.png': 'https://www.eskonas.com.tr/',
  'esenler belediyesi.png': 'https://www.esenler.bel.tr',
  'eyupsultan belediyesi.png': 'https://www.eyupsultan.bel.tr',
  'Gaziosmanpasa belediyesi.png': 'https://www.gaziosmanpasa.bel.tr',
  'İstanbul Akvaryum.png': 'https://www.istanbulakvaryum.com',
  'İstanbul_Başakşehir_FK (1).png': 'https://ibfk.com.tr/kurumsal-kimlik',
  'İstanbul Valiliği.png': 'https://www.istanbul.gov.tr',
  'marmara teknokent.png': 'https://www.marmarateknokent.com.tr',
  'Matbaacılar sitesi.png': null,
  'Metropark awm.png': 'https://metroparksefakoy.com.tr/',
  'nefes-orman-logo.png': 'https://www.nefesorman.com.tr',
  'parkekspert.png': 'http://www.parkekspert.com',
  'sarfit.jpg': 'https://www.sarfit.com.tr',
  'Sarıyer Belediyesi.png': 'https://www.sariyer.bel.tr',
  'Trik center.png': 'https://www.trikocenter.net/',
  'Vema Holding.png': 'https://www.vemaholding.com.tr/',
  'YTÜ.png': 'https://www.yildiz.edu.tr',
  'ytü Yıldız teknopark.png': 'https://www.yildizteknopark.com.tr',
}

export const referenceFiles = [
  'Arnavutlukköy belediyesi.png',
  'Bakırköy kaymakamlığı.png',
  'Bakıröy Belediyesi.png',
  'Beyoğlu kaymakamlığı.png',
  'Buyukcekmece Belediyesi.png',
  'Crowne Plaza.png',
  'Darıca belediyesi.png',
  'Gaziosmanpasa belediyesi.png',
  'Intetra.png',
  'Matbaacılar sitesi.png',
  'Metropark awm.png',
  'Sarıyer Belediyesi.png',
  'Trik center.png',
  'Vema Holding.png',
  'YTÜ.png',
  'autopia.png',
  'balıkesir Hiltonn.jpeg',
  'başakkent.png',
  'başakşehir belediyesi.png',
  'buzadası.png',
  'byuas.png',
  'demirbank-logo.svg',
  'esenler belediyesi.png',
  'eskon.png',
  'eyupsultan belediyesi.png',
  'marmara teknokent.png',
  'nefes-orman-logo.png',
  'parkekspert.png',
  'sarfit.jpg',
  'ytü Yıldız teknopark.png',
  'İstanbul Akvaryum.png',
  'İstanbul Valiliği.png',
  'İstanbul_Başakşehir_FK (1).png',
]

export const references = referenceFiles
  .filter((file) => !excludedLogos.includes(file))
  .sort((a, b) => a.localeCompare(b, 'tr'))
  .map((file) => {
    const fallback = file.replace(/\.[^.]+$/, '').replace(/[-_]/g, ' ')
    return {
      file,
      url: `/referanslar/logolar/${encodeURIComponent(file)}`,
      name: referenceNameOverrides[file] || fallback,
      website: referenceWebsiteOverrides[file] ?? null,
    }
  })
