export const pageCopy: Record<string, { titleKey: string; descriptionKey?: string; points?: string[]; image?: string }> = {
  developers: { titleKey: 'nav_developers', descriptionKey: 'sw_dev_to_dev', image: '/img/zone2.png' },
  'hardware-products.tir-kiosk': { titleKey: 'TIR Kiosk', descriptionKey: 'hardware_subtitle', image: '/img/tir-kiosk.png' },
  'hardware-products.togerbox': { titleKey: 'Togerbox', descriptionKey: 'hardware_subtitle', image: '/img/toger_parking_box_pro.webp' },
  'hardware-products.visiobox': { titleKey: 'Visiobox', descriptionKey: 'index_visiobox_desc', image: '/img/visio_parking_box_pro.webp' },
  'hardware-products.kamera-muhafaza': { titleKey: 'Kamera Muhafaza', descriptionKey: 'index_camera_housing_desc', image: '/img/kamera_muhafazasi.webp' },
  'hardware-products.kamera-montaj-kulesi': { titleKey: 'Kamera Montaj Kulesi', descriptionKey: 'hardware_subtitle', image: '/img/kamera-montaj-kulesi.png' },
  'hardware-products.ledli-reklam-paneli': { titleKey: 'Ledli Reklam Paneli', descriptionKey: 'hardware_subtitle', image: '/img/ucret_gostergesi_led_reklam.webp' },
  services: { titleKey: 'nav_services', descriptionKey: 'support_description', image: '/img/destek.png' },
  'website-pricing': { titleKey: 'Site Otopark Yönetimi', descriptionKey: 'software_section_desc', image: '/img/pages/kus_bakisi_otopark_yonetimi.webp' },
  'end-to-end': { titleKey: 'footer_end_to_end_system', descriptionKey: 'footer_cta_description', image: '/img/pages/toger_ustten_gorunus.webp' },
  'on-street': { titleKey: 'footer_on_street_parking', descriptionKey: 'software_section_desc', image: '/img/pages/yol_ustu.webp' },
  'parking-violations': { titleKey: 'footer_parking_violations', descriptionKey: 'sw_violation_desc', image: '/img/Otopark.jpg' },
  hgs: { titleKey: 'footer_hgs_payment', descriptionKey: 'hero_subtitle', image: '/img/arac-plaka-tanima.png' },
  'hgs-park': { titleKey: 'HGS Park', descriptionKey: 'hero_subtitle', image: '/img/hgspark.png' },
  references: { titleKey: 'footer_references', descriptionKey: 'hero_subtitle', image: '/img/pages/refranslarimiz.webp' },
  'bank-accounts': { titleKey: 'footer_bank_accounts' },
  'kus-bakisi': { titleKey: 'footer_birds_eye_management', descriptionKey: 'sw_birds_eye_desc', image: '/img/pages/kus_bakisi_otopark_yonetimi.webp' },
  'mobil-abonelik': { titleKey: 'footer_mobile_subscription', image: '/img/pages/mobil_uygulama_ile_park_aboneligi_nasil_yapilir.webp' },
  team: { titleKey: 'footer_team', image: '/img/pages/visiosoft_visio_takimimiz.webp' },
  'designer-tool': { titleKey: 'footer_designer_tool', image: '/img/pages/designer_kus_bakisi_cizim_araci_software.webp' },
  comparison: { titleKey: 'footer_comparison' },
  'plate-recognition-system': { titleKey: 'footer_lpr_system', descriptionKey: 'lpr_hero_description', image: '/img/pages/gercek_otopark_isvev_kus_bakisi.webp' },
  'parking-software': { titleKey: 'footer_parking_software', descriptionKey: 'software_section_desc', image: '/img/pages/kus_bakisi_otopark_yonetimi.webp' },
  'parking-reports': { titleKey: 'footer_reports', image: '/img/software/finansal-rapor-ozet.png' },
  'alpr.index': { titleKey: 'footer_lpr', descriptionKey: 'lpr_hero_description', image: '/img/arac-plaka-tanima.png' },
  'alpr.landing': { titleKey: 'footer_lpr', descriptionKey: 'lpr_page_meta_desc', image: '/img/insansiz-plaka-sistemleri.webp' },
  'legal.privacy': { titleKey: 'footer_privacy_policy' },
  'legal.terms': { titleKey: 'legal.terms' },
  'legal.sales': { titleKey: 'legal.sales' },
  'legal.distance-sales': { titleKey: 'footer_distance_sales_agreement' },
  'legal.return-policy': { titleKey: 'footer_return_policy' },
  'legal.legal': { titleKey: 'legal.legal' },
}

export function copyFor(routeName: string) {
  return pageCopy[routeName] || { titleKey: routeName, descriptionKey: 'software_section_desc' }
}
