
export const blogCopy = {
  seoTitle: 'Blog | Visiosoft',
  seoDescription: 'En son haberler, güncellemeler ve otopark teknolojisi makaleleri.',
  eyebrow: 'Blog',
  title: ['Otopark teknolojisi', 'üzerine yazılar'],
  lead: 'En son haberler, güncellemeler ve teknoloji makaleleri.',
  featuredEyebrow: 'Son yazı',
  allTitle: 'Tüm yazılar',
  read: 'Yazıyı okuyun',
  cardAction: 'Oku',
  readingTime: (minutes: number) => `${minutes} dk okuma`,
  postCount: (count: number) => `${count} yazı`,
  back: "Blog'a Dön",
  toc: 'İçindekiler',
  related: 'İlgili Yazılar',
  relatedEyebrow: 'Okumaya devam edin',
  loadingList: 'Yazılar yükleniyor',
  loadingPost: 'Yazı yükleniyor',
  errorTitle: 'Yazılar şu anda yüklenemedi',
  errorBody: 'Sunucuya ulaşılamadı. Lütfen biraz sonra yeniden deneyin.',
  emptyTitle: 'Henüz yayınlanmış yazı bulunmuyor',
  emptyBody: 'Yeni yazılar yayınlandığında bu sayfada listelenecektir.',
  homeAction: 'Ana sayfaya dönün',
  missingTitle: 'Yazı bulunamadı',
  missingBody: 'Aradığınız yazı kaldırılmış ya da adresi değişmiş olabilir.',
  postErrorTitle: 'Yazı şu anda yüklenemedi',

  coverNotes: {
    render: 'Temsilî görsel',
    demo: 'Ekran görüntüsü, demo verisi',
  },
  cta: {
    eyebrow: 'Destek',
    title: 'Otopark projeniz için destek alın',
    description: 'Plaka tanıma, otopark yazılımı ve kurulum süreçlerinde ekibimiz size yardımcı olsun.',
    primary: 'İletişime Geçin',
    secondary: 'Teklif Al',
  },
} as const
